docs/resources/blueprint.md
Fixed an issue found by Matt Kryshak. Changed "Block List" to "String" under "spec.default_addons.monitoring.resources.limits".
=> Fixed issue with blueprint doc

docs/index.md
Just needed to update the TF version table with the July release (1.0.1). 
The Blueprint OPA document was updated in a previous pull request.
=> Updated the TF versions and included the Blueprint OPA update

docs/resources/addon.md
Discrepancy was pointed  here : https://team-rafay.slack.com/archives/G012XHDH1AM/p1663168118044349
=> #RC-18556: Add missing label definition in Terraform docs

examples/resources/rafay_workload/resource.tf
We always check for version, to make sure snapshot is published : 
https://github.com/RafaySystems/rafay-config/blob/master/internal/models/v2/workload_snapshot.go#L282
Without version, its creation without publish when its v3 ; that includes rctl, swagger, terraform.
@stephan-rafay , i've tested it. do merged PR once its Okay from your side.
=> #RC-20411: Fixing workload schema by adding version field

rafay/resource_configcontext.go, rafay/resource_environment.go, rafay/resource_environmenttemplate.go, rafay/resource_resourcetemplate.go, rafay/resource_static_resource.go, rafay/utils.go
Fixes:
[Redundant approval field is getting shown in version info for http hook options in resource template created using Terraform.](https://rafaysystems.atlassian.net/browse/RC-29497)
[Other providers with null values are showing up in version info of resource template created using Terraform.](https://rafaysystems.atlassian.net/browse/RC-29472)
=> fix: ignore extra fields from eaas objects

examples/resources/rafay_resource_template/resource.tf, go.mod, go.sum, rafay/resource_resourcetemplate.go, rafay/utils.go
Fixes
[Trying to reapply/refresh/destroy resource templates with custom driver using Terraform is giving error spec.0.provider_options.0.driver: '': source data must be an array or slice, got map](https://rafaysystems.atlassian.net/browse/RC-31453)
[Re-applying/Refreshing the value of files for container type driver using Terraform is giving 'spec.0.config.0.container.0.files.test.json: '' expected type 'string', got unconvertible type '[]uint8', value.[decimal equivalent value of file value]'](https://rafaysystems.atlassian.net/browse/RC-31324)
[Terraform support : backend changes : state store, TFC and custom](https://rafaysystems.atlassian.net/browse/RC-31382)
=> fix for tf reapply / refresh / destroy of drivers

go.mod, go.sum, rafay/resource_environmenttemplate.go, rafay/resource_resourcetemplate.go
Fixes
[Trying to refresh/re-apply with refresh Terraform resources for resource templates and environment templates is giving 'Error: flatten resource spec empty input' ](https://rafaysystems.atlassian.net/browse/RC-31870)
[Re-applying Terraform resources for environment template without any changes is giving error saying its version already exists](https://rafaysystems.atlassian.net/browse/RC-31951)
Added version_state support
=> fix for refresh rt / et with no active versions and added version state

docs/resources/environment.md, rafay/resource_agent.go, rafay/resource_driver.go, rafay/resource_environmenttemplate.go, rafay/resource_repositories.go, rafay/utils.go
Fixes
[The agent in audit logs is shown as 'RCTL' for repository, gitops agent and driver created using Terraform](https://rafaysystems.atlassian.net/browse/RC-32466)
[Support new environment template fields in Terraform provider](https://rafaysystems.atlassian.net/browse/RC-32454)
=> updated agent to tf for agent, repo and driver

docs/resources/environment.md, rafay/resource_agent.go, rafay/resource_driver.go, rafay/resource_environmenttemplate.go, rafay/resource_repositories.go, rafay/utils.go
Fixes
[The agent in audit logs is shown as 'RCTL' for repository, gitops agent and driver created using Terraform](https://rafaysystems.atlassian.net/browse/RC-32466)
[Support new environment template fields in Terraform provider](https://rafaysystems.atlassian.net/browse/RC-32454)
=> updated agent to tf for agent, repo and driver (#484)

rafay/data_addon.go, rafay/resource_addon.go, rafay/resource_cluster_mesh_rule.go, rafay/resource_cluster_network_policy_rule.go, rafay/resource_namespace_mesh_rule.go, rafay/resource_namespace_network_policy_rule.go, rafay/resource_opa_constraint.go, rafay/resource_opa_constraint_template.go, rafay/resource_secrets_provider.go, rafay/resource_workload.go, rafay/resource_workloadtemplate.go, rafay/resource_ztkarule.go, rafay/structure_artifact.go
fix that is backwrd compatabile since FlattenArtifactSpec is being used from mny places. Did not want to increase the regression risk.
=> Added a flag to identify data-read vs resource-read to safely implement

rafay/resource_environmenttemplate.go
Fixes
[Provide Terraform support for agent override in environment templates](https://rafaysystems.atlassian.net/browse/RC-33991)
=> support for environment template agent overrides

go.mod, go.sum, rafay/cluster_util.go, rafay/const.go, rafay/data_aks_cluster.go, rafay/data_eks_cluster.go, rafay/resource_aks_cluster.go, rafay/resource_aks_cluster_spec.go, rafay/resource_cluster_sharing.go, rafay/resource_eks_cluster.go, rafay/resource_eks_cluster_spec.go, rafay/resource_import_cluster.go, rafay/resource_workload_cd_operator.go
Sending user agent for AKS, EKS data and resource APIs. Only sending for aks, eks v1 cluster and cluster sharing resources.
Any cluster request made by other resources like import_cluster and workload cd operator, user agent is set to empty. There is no use of user agent in these these requests.
Jira: https://rafaysystems.atlassian.net/browse/RC-34869
:warning: depends on https://github.com/RafaySystems/rctl/pull/779 (update rctl dependency)
=> Send User Agent for AKS and EKS cluster APIs

docs/data-sources/mks_cluster.md, docs/resources/mks_cluster.md, go.mod, go.sum, internal/resource_mks_cluster/mks_cluster_resource_ext.go, internal/resource_mks_cluster/mks_cluster_resource_gen.go, internal/resource_mks_cluster/mks_cluster_resource_spec.json
**EPIC Link:**
https://rafaysystems.atlassian.net/browse/RC-37566
**Testing results:**
https://jenkins.qa.stage.rafay-edge.net/job/Developers_Testing/job/master/1861/robot/report/log.html#s1-s1-s1-s13-t1
https://jenkins.qa.stage.rafay-edge.net/job/Developers_Testing/job/master/1863/robot/report/log.html#s1-s1-s1-s1-s1-t1
The test cases "CLI Cluster OCI HA Ubuntu On-prem" and "CLI Cluster AWS HA Ubuntu On-prem" failed because I used the latest master RCTL build, which doesn't yet include my kubelet args changes. Once these changes are merged to QC, these cases will be re-qualified.
Rest all are known issues which we are already working on.
=> RC-37567: Supporting Kubelet Args for MKS Clusters

internal/provider/provider.go
https://rafaysystems.atlassian.net/browse/RC-39681
**Test result:**
`rafay_mks_cluster.mks-sample-cluster: Creating...
╷
│ Error: Client Error
│ 
│   with rafay_mks_cluster.mks-sample-cluster,
│   on main.tf line 15, in resource "rafay_mks_cluster" "mks-sample-cluster":
│   15: resource "rafay_mks_cluster" "mks-sample-cluster" {
│ 
│ Unable to create cluster, got error: cluster Apply failed: unable to complete request code 404, body {"internal":"unable to hydrate
│ options rpc error: code = NotFound desc = unable to get project rpc error: code = NotFound desc = ","code":1,"external":"Not Found"}
│ 
╵`
=> RC-39681: Fixing the, Mks cluster v3 api failing with cert error

Makefile, internal/provider/mks_cluster_data_source.go, internal/resource_mks_cluster/mks_cluster_resource_ext.go
**Bug link:**
https://rafaysystems.atlassian.net/browse/RC-39824
=> RC-39824: Fixing the, kubelet_extra_args field missing in the mks terraform data schema causing attribute error

Jenkinsfile
Fixes:
```
> GOPROXY="direct" GOPRIVATE="github.com/RafaySystems/*" go mod download
go: github.com/grpc-ecosystem/grpc-gateway@v1.16.0 requires
golang.org/x/oauth2@v0.0.0-20200107190931-bf48bf16ab8d requires
cloud.google.com/go@v0.34.0 requires
go.opencensus.io@v0.23.0: unrecognized import path "go.opencensus.io": https fetch: Get "https://go.opencensus.io/?go-get=1": tls: failed to verify certificate: x509: certificate has expired or is not yet valid: “go.opencensus.io” certificate is expired
```
=> Rc xxxx remove proxy

rafay/resource_blueprint.go
If sharing is disabled we don't store projects list in backend, if user is providing project list with sharing disabled then we need to ignore it in terraform provider also to avoid diff in plan
Namespace Config Sync Type is case insensitive in rafay-hub but we stored only "Managed", "Unmanaged" in database which causes diff in terraform, need to make it case insesitive in terraform provider
Test Done
Created blueprint with the spec mentioned in testcase with terraform apply
No diff on terraform plan after apply
=> RC-40725 Fix blueprint terraform diff

rafay/utils.go
This will be taken care by changing the type to TypeSet instead of TypeList
This reverts commit 97d1654071e193a4f37885073fad43913b3908dd.
=> Revert "RC-40856: Using string sorting during object flatening too as object expand does the sorting"

docs/resources/config_context.md, docs/resources/driver.md, docs/resources/workflow_handler.md, examples/resources/rafay_workflow_handler/resource.tf, rafay/resource_workflow_handler.go
Fixes
[Missing attributes for rafay_driver resource in provider documentation under ContainerDriverConfig -> kubeOptions; but present in Swagger schema spec](https://rafaysystems.atlassian.net/browse/RC-40553)
[TF Documentation: Fix the typo under spec.files section of rafay_config_context](https://rafaysystems.atlassian.net/browse/RC-40498)
=> fix for supporting container kube options affinity

rafay/resource_resourcetemplate.go
Fixes
[Re-applying Terraform for resource templates with destroy opentofu hooks gives error](https://rafaysystems.atlassian.net/browse/RC-41568)
=> fix reapply with opentofu destroy init hook

docs/data-sources/mks_cluster.md, docs/resources/mks_cluster.md, go.mod, go.sum, internal/resource_mks_cluster/mks_cluster_resource_ext.go, internal/resource_mks_cluster/mks_cluster_resource_gen.go, internal/resource_mks_cluster/mks_cluster_resource_spec.json
**EPIC Link:**
https://rafaysystems.atlassian.net/browse/RC-36527
**Regression reports:**
**AWS API report:**
https://jenkins.qa.stage.rafay-edge.net/job/Developers_Testing/job/master/2144/robot/report/log.html#s1-s1-s1-s1-t1
**OCI API report:**
https://jenkins.qa.stage.rafay-edge.net/job/Developers_Testing/job/master/2143/robot/report/log.html#s1-s1-s1-s17
**Summary of Findings:**
There are no critical failures in the provisioning flow. Most of the observed issues are related to workload deployment failures post-provisioning. This problem has been consistently observed across multiple regression runs.
**Error message:** 
```
Workload publish status:Failed with error:cluster rauto-ocialmalinux-960585881: Install failed : 1 error occurred:
* services "workloadrauto-849963063-wordpress" is …
```
=> RC-36528: Upgrading MKS Components CRI, ETCD and Salt Minion via Platform Version

rafay/resource_eks_cluster.go, rafay/resource_eks_pod_identity.go
Schema: add DiffSuppressFunc so the flag never appears in a Day-2 plan
Update: compare old vs. new and raise an error if the flag changed
Update: strip CreateServiceAccount from the PUT payload =
=> RC-40634. Made the changes

rafay/resource_environmenttemplate.go
Fixes
[Terraform provider plugin crashes when an environment template is created with empty overrides](https://rafaysystems.atlassian.net/browse/RC-42477)
=> crash fix when providing empty overrides or depends on
