- docs/resources/eks_cluster.md
- examples/resources/rafay_eks_cluster/resource.tf
- rafay/resource_eks_cluster.go
waitflag added for cluster provision,,
terraform will be waiting until provision to complete. and cluster has to be ready..
> fix for RC-10811, i.e waitflag added

- docs/resources/aks_cluster.md
- examples/resources/rafay_aks_cluster/resource.tf
- go.mod
- go.sum
- rafay/aks_config.go
- rafay/resource_aks_cluster.go
- rafay/resource_eks_cluster.go
- rafay/util.go
to support proper state synchronization
> Modified aks cluster to support all fields as input schema 

- examples/resources/rafay_aks_cluster/providers.tf
- examples/resources/rafay_aks_cluster/resource.tf
- rafay/resource_aks_cluster.go
Fixed int value default input situation
> Int value fix

- rafay/resource_aks_cluster.go
I believe this log might be the reason for the crash
> removed extraneous log

- examples/resources/rafay_aks_cluster/resource.tf
- rafay/resource_aks_cluster.go
typo fixed in example and code
> service principal profile typo fix

- examples/resources/rafay_agent/providers.tf
- examples/resources/rafay_agent/resource.tf
- examples/resources/rafay_agent/terraform.template.tfvars
- examples/resources/rafay_agent/variables.tf
- rafay/resource_agent.go
> tested and working agent changes push

- go.mod
- rafay/eks_config.go
- rafay/resource_eks_cluster.go
> type errors and adding expand/flatten service account metadata

- examples/resources/rafay_eks_cluster/resource.tf
- rafay/eks_config.go
- rafay/resource_eks_cluster.go
added specs (expand and flatten function) for custom cni parameters
> Custom cni

- examples/resources/rafay_eks_cluster/resource.tf
- rafay/eks_config.go
- rafay/resource_eks_cluster.go
Added null check for all boolean fields
> Rc 14814 fix all fields

- rafay/resource_namespace.go
changed expand and flatten to match v3 schema
> v3 schema update

- docs/index.md
- docs/resources/eks_cluster.md
Added the "secret_encryption" to the EKS MD file.
Added the "Released" and "In Development" information to the Index MD file.
> Updated the Index and EKS files.

- examples/resources/rafay_blueprint/resource.tf
- examples/resources/rafay_project/resource.tf
- examples/resources/rafay_secret_sealer/resource.tf
- examples/resources/rafay_workloadtemplate/resource.tf
Terraform resource files for the following features - Blueprints (Fleet Upgrade, Rook Ceph), Project Resource Quota, Workload Template, Secret Sealer.
> Rc 14186 terraform provider v 3

- examples/resources/rafay_blueprint/resource.tf
- go.mod
- go.sum
- rafay/resource_blueprint.go
Reverts RafaySystems/terraform-provider-rafay#98
> Revert "RC-14598 - Golden base blueprint"

- examples/resources/rafay_namespace/resource.tf
Example for Project/namespace workspace related changes update
> RC-17049 TF Project/namespace workspace examples

- rafay/structure_artifact.go
- rafay/utils.go
Addon path and values path input error checking changes
> addon paths + values path error check

- examples/resources/rafay_secret_group/providers.tf
- examples/resources/rafay_secret_group/resource.tf
- examples/resources/rafay_secret_group/terraform.template.tfvars
- examples/resources/rafay_secret_group/variables.tf
- rafay/provider.go
- rafay/resource_project.go
- rafay/resource_secret_group.go
> finished implementing pipeline secret group

- README.md
Fixing missing `"` in README.md.
> fixing missing double quote in README.md

- examples/resources/rafay_eks_cluster/resource.tf
- go.mod
- rafay/eks_config.go
- rafay/resource_eks_cluster.go
Cherry picked commits related to identity mapping changes wrt 1.0.5-rc
> Identitymapping fix

- go.mod
- go.sum
- rafay/resource_agent.go
- rafay/resource_namespace.go
- rafay/resource_pipeline.go
- rafay/resource_repositories.go
- rafay/resource_workload.go
- rafay/resource_workloadtemplate.go
- rafay/utils.go
- Agent, Repos, pipeline, namespace, workload, workloadtemplates
> Added user impersonate support for following resources

- rafay/resource_aks_cluster.go
- rafay/resource_aks_cluster_spec.go
- rafay/resource_eks_cluster.go
- rafay/resource_eks_cluster_spec.go
- rafay/resource_import_cluster.go
- if cluster object is created set ID even if it fails to provision
> Change state saving behavior

- examples/resources/rafay_eks_cluster/resource.tf
- go.mod
- rafay/eks_config.go
- rafay/resource_eks_cluster.go
Cherry picked identity mapping changes to 1.0.5
> Identitymapping cherry pick to 1.0.5

- docs/resources/aks_cluster.md
- examples/resources/rafay_aks_cluster/resource.tf
Added pod_identity_profile content to the aks_cluster.md document.
> Added Pod Identity Profile to the AKS Cluster doc

- rafay/resource_eks_cluster.go
1. Fixing go formatting 
2. Added default value for volume iops and throughput in eks nodegroup
> Added default value for eks nodegroup volumes iops

- docs/resources/cost_profile.md
- examples/resources/rafay_cost_profile/resource.tf
- go.mod
- go.sum
- rafay/resource_cost_profile.go
> Rename ram field and remove spotRam and spotCpu from CostProfileVersionSpec

- examples/resources/rafay_aks_cluster_v3/providers.tf
- examples/resources/rafay_aks_cluster_v3/resource.tf
- examples/resources/rafay_aks_cluster_v3/terraform.template.tfvars
- examples/resources/rafay_aks_cluster_v3/testmodule.sh
- examples/resources/rafay_aks_cluster_v3/variables.tf
- go.mod
- go.sum
- rafay/provider.go
- rafay/resource_aks_cluster_v3.go
- rafay/utils.go
https://rafaysystems.atlassian.net/browse/RC-20249
Testing:
Day 0 operation: Create cluster using terraform apply - DONE
Day 2 operation: Add nodepool in spec -> terraform apply - DONE 
Delete Cluster -> terraform destroy - DONE
> RC-20249 Tf aks v3

- rafay/resource_eks_cluster.go
Genetech Fix to make version optional and amifamily not default to AmazonLinux
> RC-23951-1 fix

- examples/resources/rafay_import_cluster/resource.tf
- rafay/resource_import_cluster.go
Change description - https://rafaysystems.atlassian.net/browse/RC-25752
https://rafaysystems.atlassian.net/browse/RC-24644
https://rafaysystems.atlassian.net/browse/RC-24645
> terraform-changes-RC-24644

- rafay/resource_eks_cluster.go
>fix for https://rafaysystems.atlassian.net/browse/EE-264
> RC-25711:Terraform applies taints to incorrect nodes

- examples/resources/rafay_import_cluster/resource.tf
- rafay/resource_import_cluster.go
kubectl Bootstrap apply was being done on incorrect file path, pushing fix for that
https://rafaysystems.atlassian.net/browse/RC-24645
> bootstrap apply kubectl path fix

- docs/index.md
Added a missing quotation mark to the index.md file.
> Added missing quotation mark

- rafay/resource_import_cluster.go
rctl PR link: https://github.com/RafaySystems/rctl/pull/637
> [RC-23809]: added support for k8s provider and provision env for imported

- go.mod
- go.sum
https://rafaysystems.atlassian.net/browse/RC-20131
> Rc 20131 update rafay common deps

- docs/resources/eks_cluster.md
Added Taints to TF EKS Cluster
> Added Taints to TF EKS Cluster

- docs/index.md
Removed API secret information from the Terraform index page
> Remove API secret

- rafay/resource_blueprint.go
https://rafaysystems.atlassian.net/browse/RC-29488
> Fix panic while importing a blueprint with metadata because spec is nil

- examples/resources/rafay_gke_cluster/resource.tf
- go.mod
- go.sum
- rafay/gke_expand_util.go
- rafay/gke_flatten_util.go
Jira: https://rafaysystems.atlassian.net/browse/RC-28696
:link: https://github.com/RafaySystems/rafay-common/pull/753 (merged)
> Update GKE Node pool Auto Upgrade Config

- examples/resources/rafay_gke_cluster/output.tf
- examples/resources/rafay_gke_cluster/resource.tf
- examples/resources/rafay_gke_cluster/variables.tf
- test/resource_gke_cluster_test.go
Jira: https://rafaysystems.atlassian.net/browse/RC-29510
> Add terratest for GKE cluster

- rafay/provider.go
- rafay/resource_configcontext.go
- rafay/resource_environment.go
- rafay/resource_environmenttemplate.go
- rafay/resource_resourcetemplate.go
- rafay/resource_static_resource.go
Depends on
https://github.com/RafaySystems/rafay-hub/pull/341
> modified user agent as terraform

- examples/resources/rafay_gke_cluster/resource.tf
- go.mod
- go.sum
- rafay/cluster_v3_util.go
- rafay/gke_expand_util.go
- rafay/gke_flatten_util.go
Jira: https://rafaysystems.atlassian.net/browse/RC-30380
:link: https://github.com/RafaySystems/rafay-common/pull/825
> Update GKE node pool upgrade setting config

- docs/resources/gke_cluster.md
https://rafaysystems.atlassian.net/browse/RC-30768
https://rafaysystems.atlassian.net/browse/RC-30767
> RC-30767-RC-30768 GKE TF docs update for shared-vpc and nodes-autoupgrade

- rafay/resource_eks_cluster.go
> RC-31207: Fix permission boundary issue

- rafay/resource_cluster_sharing.go
- rafay/utils.go
https://rafaysystems.atlassian.net/browse/RC-31218
> RC-31218 ignore project id from api response

- rafay/resource_driver.go
Fixes
[Unable to create a container type driver with privileged and read only root file system enabled using Terraform](https://rafaysystems.atlassian.net/browse/RC-31320)
> updated bool value fields

- docs/resources/blueprint.md
- examples/resources/rafay_blueprint/resource.tf
- rafay/resource_blueprint.go
https://rafaysystems.atlassian.net/browse/RC-31318
https://rafaysystems.atlassian.net/browse/FR-137
> RC-31318 blueprint support for CSI secret store configuration

- docs/resources/pipeline.md
RC-25891 pipeline.md doc update for project name and custom workload name
https://rafaysystems.atlassian.net/browse/RC-25891
> RC-25891 pipeline.md doc update for project name and custom workload name

- rafay/resource_group.go
https://rafaysystems.atlassian.net/browse/RC-31715
> RC-31715-rafay_group import support added

- rafay/resource_group.go
https://rafaysystems.atlassian.net/browse/RC-31715
> RC-31715-rafay_group import support added cherry pick to v2.2.x

- docs/resources/blueprint.md
https://rafaysystems.atlassian.net/browse/RC-31318 Doc update
> RC-31318 blueprint support for CSI secret store configuration TF doc update

- examples/resources/rafay_gke_cluster/resource.tf
- go.mod
- go.sum
- rafay/gke_expand_util.go
- rafay/gke_flatten_util.go
Jira: https://rafaysystems.atlassian.net/browse/RC-32382
> Add GKE node pool reservation affinity support

- examples/resources/rafay_gke_cluster/resource.tf
- go.mod
- go.sum
- rafay/gke_expand_util.go
- rafay/gke_flatten_util.go
Jira: https://rafaysystems.atlassian.net/browse/RC-32376
Update dependency after https://github.com/RafaySystems/rafay-common/pull/960 is merged.
> GKE Reservation Affinity Support

- rafay/resource_groupassociation.go
> Ignore association already exist error and allow new user to be added to

- rafay/resource_groupassociation.go
> Ignore assoication already exist error and allow new user to be added to

- docs/resources/gke_cluster.md
Jira: https://rafaysystems.atlassian.net/browse/RC-32376
> Add GKE Reservation Affinity Doc

- rafay/data_gke_cluster.go
Jira: https://rafaysystems.atlassian.net/browse/RC-32711
> Remove extraneous fields from terraform state file for GKE cluster

- examples/resources/rafay_groupassociation/resource.tf
- rafay/resource_groupassociation.go
https://rafaysystems.atlassian.net/browse/RC-32411
RCTL dependency - https://github.com/RafaySystems/rctl/pull/742
> RC-32411 project field made optional for ADMIN roles in groupassociation tf resource

- docs/resources/gke_cluster.md
Jira: https://rafaysystems.atlassian.net/browse/RC-33860
> Update GKE doc: Add cloud logging and monitoring examples

- go.mod
- go.sum
- rafay/aks_config.go
* Fix all typos in TF provider
(cherry picked from commit 8892894254edc84a5e5c0df3ff462ec6571c34f3)
Fixed RC-33580
Updated rafay-common dependency
> RC-33321 Fix AKS Terraform marshalling issues

- go.mod
- go.sum
- rafay/aks_config.go
* Fix all typos in TF provider
(cherry picked from commit 8892894254edc84a5e5c0df3ff462ec6571c34f3)
Fixed RC-33580
Updated rafay-common dependency
(cherry picked from commit 056181a66b49d0df9d1e5c114af99cf533670249)
> Terraform Provider typos fix v2.5.x Prod Patch

- Makefile
- rafay/migrate/aks/fromV1/migrate.go
- rafay/migrate/aks/fromV1/migrate_test.go
- rafay/resource_aks_cluster.go
(cherry picked from commit c1c6ef8e1371929299f4efabc0dff338a05ba0f7)
> RC 34278 v2.6.x

- docs/resources/gke_cluster.md
- examples/resources/rafay_gke_cluster/resource.tf
- rafay/gke_expand_util.go
- rafay/gke_flatten_util.go
Jira: https://rafaysystems.atlassian.net/browse/RC-34510
> feat(GKE): add terraform support for dataplaneV2 & CalicoNetworkPolicy in clusterNetwork config

- rafay/resource_eks_cluster.go
Jira: https://rafaysystems.atlassian.net/browse/RC-35067
> fix(EKS): nil checks for rawState

- rafay/resource_eks_cluster.go
Jira: https://rafaysystems.atlassian.net/browse/RC-35067
> fix(EKS): nil checks for rawState lists

- rafay/resource_environmenttemplate.go
- rafay/resource_resourcetemplate.go
- rafay/utils.go
Fixes
[Terraform apply action without any changes in resource/environment templates spec is recognizing the change in hook name](https://rafaysystems.atlassian.net/browse/RC-34859)
> fix to handle unwarranted differences

- docs/resources/gke_cluster.md
- examples/resources/rafay_gke_cluster/resource.tf
- rafay/gke_expand_util.go
- rafay/gke_flatten_util.go
https://rafaysystems.atlassian.net/browse/RC-34610
> feat(GKE): add support for additional attributes of dataplaneV2

- docs/resources/gke_cluster.md
- examples/resources/rafay_gke_cluster/resource.tf
- go.mod
- go.sum
- rafay/gke_expand_util.go
- rafay/gke_flatten_util.go
Jira:
- https://rafaysystems.atlassian.net/browse/RC-34502
- https://rafaysystems.atlassian.net/browse/RC-34610
> Support to enable Network Policy and Dataplane V2 for GKE Clusters

- rafay/gke_flatten_util.go
Jira: https://rafaysystems.atlassian.net/browse/RC-35377
> fix GKE unnecessary diff for private cluster config

- docs/resources/gke_cluster.md
Jira: https://rafaysystems.atlassian.net/browse/RC-35467
> GKE doc: Explain usage of ${ROOT_DIR} in pre-bootstrap commands

- docs/resources/gke_cluster.md
Jira: https://rafaysystems.atlassian.net/browse/RC-35289
> GKE doc: Add various examples

- rafay/data_gke_cluster.go
- rafay/gke_schema.go
- rafay/resource_gke_cluster.go
Jira: https://rafaysystems.atlassian.net/browse/RC-35330
> GKE: Removed extra fields from state file

- rafay/gke_flatten_util.go
Jira: https://rafaysystems.atlassian.net/browse/RC-35378
> Fix unnecessary diff for GKE cluster GPU config

- rafay/data_eks_cluster.go
Jira: https://rafaysystems.atlassian.net/browse/RC-35411
> fix(EKS): add nil checks to rawState for data source

- rafay/gke_schema.go
- rafay/resource_gke_cluster.go
Jira: https://rafaysystems.atlassian.net/browse/RC-35464
> Fix Terraform import for GKE clusters

- docs/resources/gke_cluster.md
Jira: https://rafaysystems.atlassian.net/browse/RC-35840
> Update GKE node pool upgrade settings

- .github/workflows/release.yml
> go releaser fix

- Makefile
Attempting to fix 
[Terraform provider: generating imports is failing with latest terraform provider master](https://rafaysystems.atlassian.net/browse/RC-35866)
> disabling cgo during while building binary

- docs/resources/config_context.md
- examples/resources/rafay_config_context/resource.tf
- rafay/utils.go
Fixes
[Change the file data input and add override type and options for environment variables and files in config contexts](https://rafaysystems.atlassian.net/browse/RC-35896)
> updated file field and options for envvars, files in config contexts

- docs/resources/eks_cluster.md
Jira: https://rafaysystems.atlassian.net/browse/RC-36392
> fix(EKS): update EKS spec in docs

- docs/resources/cost_profile.md
- examples/resources/rafay_cost_profile/resource.tf
- go.mod
- go.sum
- rafay/resource_cost_profile.go
RC 36656 Gcp cost profile changes
https://rafaysystems.atlassian.net/browse/RC-36656
> RC 36656 gcp cost profile changes

- docs/resources/resource_template.md
Fixes
[Change all occurrences of hooks to tasks and remove container and http type tasks for custom provider in Rafay Terraform docs](https://rafaysystems.atlassian.net/browse/RC-37027)
> corrected resource template docs for custom provider tasks

- docs/resources/aks_workload_identity.md
- examples/resources/rafay_aks_cluster/resource.tf
- examples/resources/rafay_aks_cluster_v3/resource.tf
- examples/resources/rafay_aks_workload_identity/resource.tf
- go.mod
- go.sum
- rafay/aks_config.go
- rafay/resource_aks_cluster.go
- rafay/resource_aks_cluster_v3.go
- rafay/resource_aks_workload_identity.go
* Added v1 config bundlers for edge resources
* Added v3 config bundlers for edge resources
> Fixed RC-37253

- internal/resource_mks_cluster/mks_cluster_resource_ext.go
https://rafaysystems.atlassian.net/browse/RC-37574
> v2.11.x-mks-tf: Return diags if apply/delete fails

- internal/resource_mks_cluster/mks_cluster_resource_ext.go
https://rafaysystems.atlassian.net/browse/RC-37574
> mks-tf: Return diags if apply/delete fails

- docs/resources/aks_cluster.md
- docs/resources/aks_cluster_v3.md
- docs/resources/aks_workload_identity.md
- rafay/resource_aks_workload_identity.go
(cherry picked from commit 92898e2bb2ecc3cb2490f5ed6598713aaf0d7705)
> RC-37547 Updated docs

- docs/resources/environment.md
- docs/resources/environment_template.md
- go.mod
- go.sum
- rafay/resource_environmenttemplate.go
Fixes
- to handle empty schedule contexts
Added
- [Terraform documentation for schedules ](https://rafaysystems.atlassian.net/browse/RC-37625)
> fix to handle empty schedule context

- rafay/resource_environment.go
Fixes
[Terraform is crashing when we try to optout for environments](https://rafaysystems.atlassian.net/browse/RC-38154)
> fix to consider schedule optouts from environment

- docs/resources/breakglassaccess.md
- examples/resources/rafay_break_glass_access/resource.tf
- rafay/resource_breakglassaccess.go
Modified expiry type to float64, include field timezone
Unit Test Done
- terraform init && terraform apply on Qc, with sample resource spec
> RC-38515 - change expiry type to float64, include timezone field

- docs/resources/cost_profile.md
- examples/resources/rafay_cost_profile/resource.tf
https://rafaysystems.atlassian.net/browse/RC-38465
> RC-38465: Marked deprecated and removed fields for AWS and Azure

- rafay/resource_ztkarule.go
terraform destroy was failing for ztka rule. Added nil check 
Tests done - on testbed ran terraform create, terraform destroy
> RC-39003 check nil object while expanding for destroy object

- internal/resource_mks_cluster/mks_cluster_resource_gen.go
- internal/resource_mks_cluster/mks_cluster_resource_spec.json
https://jenkins.qa.stage.rafay-edge.net/view/Automation_Dev_Test/job/dev-testing/job/master/2376/
> Custom CNI changes

- Jenkinsfile
(cherry picked from commit d7439024a17e3722abe655a9af47392333d5adc0)
> upgrade golang version

- rafay/resource_group.go
test - tried on testbed with updated terraform build, group state is preserved
> RC-39254 for group check if error is not 404 not found before dropping the object

- docs/resources/blueprint.md
- go.mod
- go.sum
- rafay/resource_blueprint.go
1. Verified custom bp creation via terraform and validated the cni add-ons were exluded from systemc components.
> Avoding CNI add-on for custom bp

- internal/provider/provider.go
https://rafaysystems.atlassian.net/browse/RC-39681
> RC-39681: Fixing the, Mks cluster v3 api failing with cert error

- docs/resources/environment_template.md
- docs/resources/resource_template.md
- rafay/resource_environmenttemplate.go
- rafay/resource_resourcetemplate.go
Fixes
Support all version types in git sync and terraform
> changes to support rt and et version state updates

- Jenkinsfile
same as https://github.com/RafaySystems/terraform-provider-rafay/pull/796
> change proxy

- rafay/resource_user.go
> RC-39770 - set group for user even if empty

- go.mod
- go.sum
In rctl binary the function used to ignore first name last name and default to " ". Changed that to accept user provided inputs.
> RC-40117 - update rctl binary

- docs/resources/cluster_override.md
- examples/resources/rafay_cluster_override/resource.tf
JIRA: https://rafaysystems.atlassian.net/browse/RC-40429
Update documentation example for cluster quota overrides
> RC-40429: Update cluster quota override example and doc

- docs/resources/eks_cluster.md
Jira: https://rafaysystems.atlassian.net/browse/RC-40514
> docs: add missing instances_distribution block

- rafay/resource_resourcetemplate.go
Fixes
[Unable to create inline config contexts using Terraform in resource/environment templates](https://rafaysystems.atlassian.net/browse/RC-40614)
> changes to support inline config context

- docs/resources/blueprint.md
- doc for type
- doc for drift_webhook
> RC-40584 update doc for blueprint

- rafay/aks_config.go
Regression reports: https://rafaysystems.atlassian.net/browse/RC-40716?focusedCommentId=82402
> [RC-40716]: removed omitempty from create_account field

- go.mod
- go.sum
- rafay/resource_blueprint.go
- Handle case when user provide sharing true but project list is not empty
- Handle case when user does not provide drift_Webhook 
tested terrafrom plan, apply, plan to check no diff was shown
> RC-40725 Fix diff for blueprint terraform 

- rafay/resource_blueprint.go
Need to update rafay-common 
(cherry picked from commit 8e089eed01e5526d6355672ebde26ee10aa97e0c)
> handle projects sharing and drift webhook diff

- docs/resources/driver.md
- docs/resources/environment_template.md
- docs/resources/resource_template.md
- docs/resources/workflow_handler.md
Fixed
[TF Documentation: Inputs and Outputs are shown as Required fields under spec for rafay_driver; but these are optional according to schema](https://rafaysystems.atlassian.net/browse/RC-40994)
Added workflowhandler docs to rt and et and update fields.
> Rc 40994 v3.3.x

- rafay/resource_cluster_sharing.go
Fixed the refresh issue.
Root cause:
the flattenClusterSharingSpec was reading the local state and then performing the flattening without reading from the remote(actual).
Test:
1. Shared the cluster with project -> defaultproject using the terraform.
resource.tf used:
```
resource "rafay_cluster_sharing" "demo-terraform-specific" {
clustername = "mks-cluster-sharing-1"
project     = "manish"
sharing {
all = false
projects {
name = "defaultproject"
}
}
}
```
2.  Unshared the cluster from UI .
3.  pefromed terraform plan -> identified the changes between the current tf state and the remote state.(actual state)
4. terraform apply
5. Terraform apply successful and the cluster shared with defaultproject.
Test 2:
6. terraform plan -> No changes detected.
Since this change is made to the cluster …
> RC-39009.Fixed the refresh issue

- docs/resources/driver.md
- docs/resources/workflow_handler.md
- rafay/resource_configcontext.go
- rafay/resource_driver.go
- rafay/resource_environment.go
- rafay/resource_environmenttemplate.go
- rafay/resource_resourcetemplate.go
- rafay/resource_static_resource.go
- rafay/resource_workflow_handler.go
- rafay/utils.go
Fixes
[TF: rafay_driver: polling_config TypeList object configured via Terraform is not being honored in the GET call of UI/Swagger](https://rafaysystems.atlassian.net/browse/RC-41050)
[TF: Documentation: rafay_driver resource shows a spec for "compound ref"](https://rafaysystems.atlassian.net/browse/RC-41051)
[Terraform provider plugin crashed on terraform plan post apply v 3.3.x :70](https://rafaysystems.atlassian.net/browse/RC-41143)
> support for polling config and update driver and wfhandler documentation

- rafay/resource_configcontext.go
- rafay/resource_driver.go
- rafay/resource_environment.go
- rafay/resource_environmenttemplate.go
- rafay/resource_resourcetemplate.go
- rafay/resource_static_resource.go
- rafay/resource_workflow_handler.go
Fixes
[diff issue in sharing spec for all EM resources](https://rafaysystems.atlassian.net/browse/RC-41154)
> suppress diff issue in sharing spec

- docs/resources/blueprint.md
- docs/resources/project.md
- examples/resources/rafay_blueprint/resource.tf
Remove deperecated logging feature from blueprint docs and examples
Corrected the docs for cluster namespace quota
> RC-41142 RC-41140 : docs and examples changes for blueprints and projects

- docs/resources/driver.md
- docs/resources/environment.md
- docs/resources/environment_template.md
- docs/resources/resource_template.md
- docs/resources/workflow_handler.md
Fixes
[Fixed tf docs reference links](https://rafaysystems.atlassian.net/browse/RC-40508)
> fixed eaas tf docs reference links

- docs/resources/blueprint.md
- docs/resources/project.md
- examples/resources/rafay_blueprint/resource.tf
https://github.com/RafaySystems/terraform-provider-rafay/pull/941
> RC-41142 RC-41140 v3.4.x : docs and examples changes for blueprints and projects

- rafay/resource_project.go
TODO: need to update go.mod after this https://github.com/RafaySystems/rafay-common/pull/1505
> RC-41222: supported fail-on-exists flag for project resource

- rafay/resource_namespace.go
JIRA: https://rafaysystems.atlassian.net/browse/RC-41176
> RC-41176: Print reason for namespace publish error

- rafay/download_kube_config.go
JIRA: https://rafaysystems.atlassian.net/browse/RC-36171
> RC-36171: Fix err msg typo and return err if encountered

- docs/resources/environment_template.md
- docs/resources/resource_template.md
Docs changes for 
[Added docs for config context inline under rt and et](https://rafaysystems.atlassian.net/browse/RC-38166)
> added docs to config context inline for rt and et

- go.mod
- go.sum
- rafay/const.go
- rafay/resource_aks_cluster.go
- rafay/resource_aks_cluster_spec.go
- rafay/resource_cluster_sharing.go
- rafay/resource_cluster_sharing_single.go
- rafay/resource_eks_cluster.go
- rafay/resource_eks_cluster_spec.go
Jira: https://rafaysystems.atlassian.net/browse/RC-40541
> Fix cluster sharing issue

- rafay/const.go
- rafay/resource_aks_cluster.go
- rafay/resource_aks_cluster_spec.go
- rafay/resource_cluster_sharing.go
- rafay/resource_cluster_sharing_single.go
- rafay/resource_eks_cluster.go
- rafay/resource_eks_cluster_spec.go
* Fix cluster sharing issue
* Handle conflicts between cluster sharings
* Add cluster sharing external changes to rafay_cluster_sharing resource
:warning: Update rctl dependency after https://github.com/RafaySystems/rctl/pull/896 is merged.
> RC-40541 Patch 3.4

- go.mod
- go.sum
- rafay/const.go
- rafay/resource_aks_cluster.go
- rafay/resource_aks_cluster_spec.go
- rafay/resource_cluster_sharing.go
- rafay/resource_cluster_sharing_single.go
- rafay/resource_eks_cluster.go
- rafay/resource_eks_cluster_spec.go
* Fix cluster sharing issue
* Handle conflicts between cluster sharings
* Add cluster sharing external changes to rafay_cluster_sharing resource
---------
> RC-40541 Patch 3.3

- go.mod
- go.sum
Jira: https://rafaysystems.atlassian.net/browse/RC-41681
> Fix 3.4.x build issue

- examples/resources/rafay_static_resource/resource.tf
- go.mod
- go.sum
- rafay/resource_static_resource.go
Fixes
[Terraform apply without changes is showing a diff in spec.variables for static resources](https://rafaysystems.atlassian.net/browse/RC-41733)
> updated rafay-common deps to enforce variables validation

- go.mod
- go.sum
- internal/provider/cluster_util.go
- internal/provider/const.go
- internal/provider/mks_cluster_resource.go
- rafay/const.go
- rafay/resource_aks_cluster.go
- rafay/resource_aks_cluster_v3.go
- rafay/resource_cluster_sharing.go
- rafay/resource_cluster_sharing_single.go
- rafay/resource_eks_cluster.go
- rafay/resource_gke_cluster.go
- rafay/utils.go
Jira: https://rafaysystems.atlassian.net/browse/EE-889
:warning: Need to update rctl dependency after rctl pr is merged.
https://github.com/RafaySystems/rctl/pull/922
> Fix MKS cluster sharing terraform issue

- rafay/resource_user.go
> RC-41858: reverted RC-40117 and fixed diff for API user

- rafay/resource_cluster_sharing.go
Jira: https://rafaysystems.atlassian.net/browse/RC-42166
> Fix Cluster Sharing TF plan issue

- go.mod
- go.sum
- rafay/resource_aks_workload_identity.go
Verified the blocker fix in QC
> [RC-40749]: Using timeout configuration support to fix latency issues

- Makefile
https://rafaysystems.atlassian.net/browse/RC-42354
> Fix darwin arm64 missing issue

- internal/resource_mks_cluster/mks_cluster_resource_gen.go
**Bug link:**
https://rafaysystems.atlassian.net/browse/RC-42584
> RC-42584: Gen files update

- docs/resources/agent.md
PRs to be merged only after checking all these items:
> docker agent docs update

- docs/resources/agent.md
PRs to be merged only after checking all these items:
> update docs for docker limit

- docs/resources/environment_template.md
PRs to be merged only after checking all these items:
> corrected staggered schedule docs in environment template

- docs/resources/agent.md
PRs to be merged only after checking all these items:
> keep docker specific limits

- docs/resources/namespace.md
- go.mod
- go.sum
- rafay/resource_namespace.go
Cherry-picked from: https://github.com/RafaySystems/terraform-provider-rafay/pull/1062
> RC-42868(cherry-pick): Handle ns publish partial ready state and context deadline exceeded scenario

- go.mod
- go.sum
- rafay/resource_import_cluster.go
* user_agent support for UpdateCluster clal
* avoid system_labels diff for import_cluster resource
* added user_agent support for editLabels
* fixing day-2 system labels edit
* deps update..
update deps..
> [RC-40108]: manage environment created cluster attributes (#985)

- docs/resources/environment_template.md
- docs/resources/resource_template.md
- go.mod
- go.sum
[Crashloop-backoff error seen in rafay-hub services](https://rafaysystems.atlassian.net/browse/RC-43068)
> updated rafay-common deps

- rafay/utils.go
Fixes
[Unable to refresh/import the state of workflow handler in custom workflows schedule in environment templates using Terraform](https://rafaysystems.atlassian.net/browse/RC-42290)
> fixed refresh or import wh for schedules and custom rt

- docs/resources/chargeback_group.md
https://rafaysystems.atlassian.net/browse/RC-41870
https://rafaysystems.atlassian.net/browse/RC-41872
> RC-41872 Updating TF doc for the chargeback report enhancement
